config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :members
  get 'home/about'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def about
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: %i[ show edit update destroy ]

  # GET /members or /members.json
  def index
    @members = Member.all
  end

  # GET /members/1 or /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members or /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: "Member was successfully created." }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1 or /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: "Member was successfully updated." }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1 or /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: "Member was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def member_params
      params.require(:member).permit(:first_name, :last_name, :email, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  <%= link_to 'HomePage', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item">
        <%= link_to 'About test-App', home_about_path, class: "nav-link" %>
      </li>  
      <li class="nav-item">
        <%= link_to 'Sign in', new_user_session_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Edit Profile Details', edit_user_registration_path, class: "nav-link" %>
      </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Actions Dropdown List
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to 'View Members', members_path, class: "dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to 'Add Member', new_member_path, class: "dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
          </ul>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About the app</h1>
<h2>This is the testing app. Build using ROR for testing puposes</h2>

app/views/home/index.html.erb
<h1>Hello World</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-primary alert-dismissible" role="alert" id="liveAlert">
  <%=notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <title>Library Application (Only for testing purposes!)</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">

    <br/>
    
    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>

    <%= yield %>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/members/_form.html.erb
<%= form_with(model: member) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
        <% member.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>

  <div class="field form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  </div>

  <div class="field form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class:"form-control", placeholder:"Email"  %>
  </div>

  <div class="field form-group">
    <%= form.label :phone %>
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone Number"  %>
  </div>

  <br/>

  <div class="actions">
    <%= form.submit class:'btn btn-dark'%>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>
<br/>
<%= render 'form', member: @member,  class:"btn btn-primary" %>
<br/>
<%= link_to 'Show', @member,  class:"btn btn-secondary" %> |
<%= link_to 'Back', members_path,  class:"btn btn-secondary" %>

app/views/members/index.html.erb
<h1>Members List</h1>

<table class="table table-striped table-hover table-bordered">
  <thead class="table-dark">
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.first_name %></td>
        <td><%= member.last_name %></td>
        <td><%= member.email %></td>
        <td><%= member.phone %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path, class:"btn btn-dark" %>

app/views/members/new.html.erb
<h1>Fill the details to Add a New Member</h1>

<%= render 'form', member: @member %>
<br/>
<%= link_to 'Back', members_path, class:"btn btn-secondary" %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @member.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @member.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @member.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @member.phone %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>